[
  {
    Title: 'Blade Runner',
    Year: '1982',
    Rated: 'R',
    Released: '25 Jun 1982',
    Runtime: '117 min',
    Genre: 'Action, Drama, Sci-Fi',
    Director: 'Ridley Scott',
    Writer: 'Hampton Fancher, David Webb Peoples, Philip K. Dick',
    Actors: 'Harrison Ford, Rutger Hauer, Sean Young',
    Plot: 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.',
    Language: 'English, German, Cantonese, Japanese, Hungarian, Arabic, Korean',
    Country: 'United States, United Kingdom',
    Awards: 'Nominated for 2 Oscars. 13 wins & 22 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [ [Object], [Object], [Object] ],
    Metascore: '84',
    imdbRating: '8.1',
    imdbVotes: '842,743',
    imdbID: 'tt0083658',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$32,914,489',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Blade Runner 2049',
    Year: '2017',
    Rated: 'R',
    Released: '06 Oct 2017',
    Runtime: '164 min',
    Genre: 'Action, Drama, Mystery',
    Director: 'Denis Villeneuve',
    Writer: 'Hampton Fancher, Michael Green, Philip K. Dick',
    Actors: 'Harrison Ford, Ryan Gosling, Ana de Armas',
    Plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    Language: 'English',
    Country: 'United States, United Kingdom, Canada, Spain',
    Awards: 'Won 2 Oscars. 100 wins & 163 nominations total',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg',
    Ratings: [ [Object], [Object], [Object] ],
    Metascore: '81',
    imdbRating: '8.0',
    imdbVotes: '695,699',
    imdbID: 'tt1856101',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: '$92,071,675',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Blade Runner: Black Out 2022',
    Year: '2017',
    Rated: 'N/A',
    Released: '26 Sep 2017',
    Runtime: '15 min',
    Genre: 'Animation, Short, Sci-Fi',
    Director: "Shin'ichirô Watanabe",
    Writer: "Shin'ichirô Watanabe",
    Actors: 'Jovan Jackson, Luci Christian, Bryson Baugus, Edward James Olmos',
    Plot: 'In 2022, a powerful weapon causes a global blackout that has massive implications all over the world.',
    Language: 'English',
    Country: 'USA, Japan',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZGNiNmNiMTctMDI4OS00OWYxLWE4ZWEtZjFkZjU4ZmY5YzEyXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '7.3',
    imdbVotes: '7,731',
    imdbID: 'tt7428594',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Dangerous Days: Making Blade Runner',
    Year: '2007',
    Rated: 'N/A',
    Released: '18 Dec 2007',
    Runtime: '214 min',
    Genre: 'Documentary',
    Director: 'Charles de Lauzirika',
    Writer: 'N/A',
    Actors: 'Daryl Hannah, Michael Deeley, Harrison Ford, Joanna Cassidy',
    Plot: 'The definitive three-and-a-half hour documentary about the troubled creation and enduring legacy of the science fiction classic Blade Runner (1982), culled from 80 interviews and hours of never-before-seen outtakes and lost footage.',
    Language: 'English',
    Country: 'USA',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzI2NjU0MjY4MF5BMl5BanBnXkFtZTgwMjM0NDQzNjE@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '8.3',
    imdbVotes: '1,886',
    imdbID: 'tt1080585',
    Type: 'movie',
    DVD: '18 Dec 2007',
    BoxOffice: 'N/A',
    Production: 'Warner Home Video',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Oscar Pistorius: Blade Runner Killer',
    Year: '2017',
    Rated: 'TV-14',
    Released: '08 Nov 2017',
    Runtime: '90 min',
    Genre: 'Drama',
    Director: 'Norman Stone',
    Writer: 'Amber Benson, Adam Freeman',
    Actors: 'Andreas Damm, Toni Garrn, Timothy Davis',
    Plot: "Oscar Pistorius, a South African Paralympian, rose to fame through a romantic relationship with model Reeva Steenkamp, leading to her tragic death on Valentine's Day.",
    Language: 'English',
    Country: 'United States',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNjZiMjYwMTMtNjY1Yi00MGI5LTk1MGUtOTdhMDAzMWJjMjBhXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '5.1',
    imdbVotes: '483',
    imdbID: 'tt7445510',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: "On the Edge of 'Blade Runner'",
    Year: '2000',
    Rated: 'N/A',
    Released: '15 Jul 2000',
    Runtime: '52 min',
    Genre: 'Documentary',
    Director: 'Andrew Abbott',
    Writer: 'Mark Kermode',
    Actors: 'Mark Kermode, Brian Aldiss, Michael Arick',
    Plot: 'About the epic film "Blade Runner," giving insights into its history with interviews of Ridley Scott, the writers, and nearly all of the cast. There are also interviews with production staff, giving details into the creative proce...',
    Language: 'English',
    Country: 'United Kingdom',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMGRhY2RlMWYtOGQ4Yi00NmMxLWJiZDUtZmRkZjYzYWRlNmExXkEyXkFqcGdeQXVyMTQxNzE3ODA3._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '7.5',
    imdbVotes: '327',
    imdbID: 'tt0281011',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Phenomenon Blade Runner',
    Year: '2021',
    Rated: 'N/A',
    Released: '27 May 2021',
    Runtime: '53 min',
    Genre: 'Documentary',
    Director: 'Boris Hars-Tschachotin',
    Writer: 'Boris Hars-Tschachotin',
    Actors: 'Joanna Cassidy, Harrison Ford, Ryan Gosling',
    Plot: 'In 1982 a film came to the cinema that is set in the near future of Los Angeles in 2019 and itself changed the future of cinema as it is one of the most influential science fiction films ever and achieved cult status among cinema ...',
    Language: 'German, English',
    Country: 'Germany',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMmQ1NDA5YWMtMGE5NC00MTU1LTkxNTMtZThkNDg4ZTNjODUzXkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '6.5',
    imdbVotes: '102',
    imdbID: 'tt14730032',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Blade Runner',
    Year: '2013',
    Rated: 'N/A',
    Released: 'N/A',
    Runtime: '1 min',
    Genre: 'Animation, Short, Drama',
    Director: 'Philip Askins',
    Writer: 'N/A',
    Actors: 'Nicolas Lees',
    Plot: 'N/A',
    Language: 'English',
    Country: 'United Kingdom',
    Awards: '1 win',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzRiNWNmOGMtM2E1Ny00YzBjLWJjZWEtNGJhZDBlNTk2ODI0XkEyXkFqcGc@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '7.0',
    imdbVotes: '85',
    imdbID: 'tt2797762',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Blade Runner: Deleted and Alternate Scenes',
    Year: '2007',
    Rated: 'N/A',
    Released: '18 Dec 2007',
    Runtime: '47 min',
    Genre: 'Documentary, Sci-Fi',
    Director: 'N/A',
    Writer: 'N/A',
    Actors: 'Ben Astar, Joanna Cassidy, Harrison Ford, Daryl Hannah',
    Plot: 'A newly-assembled narrative of 24 deleted and alternate scenes from the film Blade Runner (1982), presented as an abridged version of the film itself.',
    Language: 'English',
    Country: 'USA',
    Awards: 'N/A',
    Poster: 'N/A',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '8.7',
    imdbVotes: '80',
    imdbID: 'tt1165254',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  },
  {
    Title: 'Blade Runner 2049: To Be Human: - Casting Blade Runner 2049',
    Year: '2018',
    Rated: 'N/A',
    Released: '16 Jan 2018',
    Runtime: 'N/A',
    Genre: 'Documentary, Short',
    Director: 'N/A',
    Writer: 'N/A',
    Actors: 'Dave Bautista, Mackenzie Davis, Ana de Armas, Harrison Ford',
    Plot: 'A behind the scenes look at the casting of Blade Runner 2049 originally produced for the home entertainment release.',
    Language: 'English',
    Country: 'USA',
    Awards: 'N/A',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjRjZDVkMTMtMzZlZC00YzBhLWJkYjQtNWVjNzVhNzg1NjAxXkEyXkFqcGdeQXVyMjA3NzQyMA@@._V1_SX300.jpg',
    Ratings: [ [Object] ],
    Metascore: 'N/A',
    imdbRating: '7.4',
    imdbVotes: '65',
    imdbID: 'tt7879362',
    Type: 'movie',
    DVD: 'N/A',
    BoxOffice: 'N/A',
    Production: 'N/A',
    Website: 'N/A',
    Response: 'True'
  }
]